`timescale 1 ns / 100 ps

module skeleton_tb;

    // Testbench signals
    reg clock;
    reg reset;

    // Clocks generated by the skeleton module
    wire imem_clock;
    wire dmem_clock;
    wire processor_clock;
    wire regfile_clock;

    // Declare integer for loop
    integer i;

    // Instantiate the skeleton module
    skeleton uut (
        .clock(clock),
        .reset(reset),
        .imem_clock(imem_clock),
        .dmem_clock(dmem_clock),
        .processor_clock(processor_clock),
        .regfile_clock(regfile_clock)
    );

    // Generate main clock (50 MHz, 20 ns period)
    always #10 clock = ~clock;

    initial begin
        // Display initial message to confirm testbench starts
        $display("Starting testbench...");

        // Initialize clock and reset
        clock = 0;
        reset = 1;
        
        // Wait a few cycles, then deassert reset
        #20 reset = 0;
        $display("Reset deasserted");

        // Run the processor for several cycles, checking registers periodically
        repeat (4) @(posedge processor_clock);
        $display("Checking register values after 4 processor cycles...");
        for (i = 0; i < 32; i = i + 1) begin
            $display("Register %0d: %h", i, uut.my_regfile.registers[i]);
        end

        // Repeat this in increments to allow more instructions to execute
        repeat (4) @(posedge processor_clock);
        $display("Checking register values after 8 processor cycles...");
        for (i = 0; i < 32; i = i + 1) begin
            $display("Register %0d: %h", i, uut.my_regfile.registers[i]);
        end

        repeat (4) @(posedge processor_clock);
        $display("Checking register values after 12 processor cycles...");
        for (i = 0; i < 32; i = i + 1) begin
            $display("Register %0d: %h", i, uut.my_regfile.registers[i]);
        end

        // Let the processor run for more cycles to observe any additional updates
        repeat (8) @(posedge processor_clock);
        $display("Checking register values after 20 processor cycles...");
        for (i = 0; i < 32; i = i + 1) begin
            $display("Register %0d: %h", i, uut.my_regfile.registers[i]);
        end

        // Final check after more cycles
        repeat (8) @(posedge processor_clock);
        $display("Final register values after 28 processor cycles:");
        for (i = 0; i < 32; i = i + 1) begin
            $display("Register %0d: %h", i, uut.my_regfile.registers[i]);
        end

        // End simulation
        $display("Ending testbench.");
        $finish;
    end

endmodule
